export const NEXT_PAGE = `NEXT_PAGE`
export const PREV_PAGE = `PREV_PAGE`
export const SET_CURRENT = `SET_CURRENT`

export const GET_ARTICLES_FAILED = `GET_ARTICLES_FAILED`
export const GET_ARTICLES_SUCCESS = `GET_ARTICLES_SUCCESS`
export const GET_ARTICLES_REQUESTED = `GET_ARTICLES_REQUESTED`

export const DELETE_ARICLE = `DELETE_ARTICLE`
export const UPDATE_ARTICLE = `UPDATE_ARTICLE`
export const ADD_ARTICLE=  `ADD_ARTICLE`

export const HIDE_ADD = `HIDE_ADD`
export const REPLACE_DATA = `REPLACE_DATA`